theme = "tokyonight_moon"

[editor]
scroll-lines = 1
cursorline = true
auto-save = false
completion-trigger-len = 1
bufferline = "multiple"
true-color = true
color-modes = true
rulers = [120]
idle-timeout = 50
line-number = "relative"
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spacer", "version-control", "read-only-indicator", "file-modification-indicator", "spinner"]
center = ["file-name", "diagnostics"]
right = ["workspace-diagnostics", "primary-selection-length", "position", "position-percentage", "total-line-numbers", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.select = "SELECT"
mode.insert = "INSERT"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = ""

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
"'" = "'"

[editor.lsp]
display-messages = true
display-inlay-hints = true
display-signature-help-docs = true

# [editor.inline-diagnostics]
# other-lines = "error"
# cursor-line = "hint"

[keys.insert]
C-space = "signature_help"
